---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart fluent-bit
  systemd:
    name: fluent-bit
    state: restarted
    daemon_reload: yes

- name: reload fluent-bit
  systemd:
    name: fluent-bit
    state: reloaded
