---
# defaults file for deploy_herlmchart_stac
## ERROR : ERROR! couldn't resolve module/action 'community.kubernetes.helm_repository'. This often indicates a misspelling, missing collection, or incorrect module path.
## WARNING : Depend of community.kubernetes.helm_repository
## INSTALL : ansible-galaxy collection install community.kubernetes

helm_repo_name: ""
helm_repo_url: ""
chart_name: ""
namespace: ""
release_name: ""