---
galaxy_info:
  author: "A&ECoding"
  description: "RÃ´le Ansible to Download Pull models on Ollama windows"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - ollama
    - ai
dependencies: []