---
galaxy_info:
  author: A&E Coding
  description: Installation of MinIO Client for Linux/Unix Distribution
  company: A&E Coding
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - '18.04'
        - '20.04'
        - '22.04'
    - name: CentOS
      versions:
        - '7'
        - '8'
    - name: RedHat
      versions:
        - '7'
        - '8'
        - '9'
  galaxy_tags:
    - minio

dependencies: []