galaxy_info:
  author: "A&ECoding"
  description: "RÃ´le Ansible to configure Apache2 & Deploy vhost for Proxy or Website"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - linux
    - apache2
    - a2en*
dependencies: []