galaxy_info:
  author: "A&ECoding"
  description: "RÃ´le Ansible to manage package from chocolatey"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - package
    - Chocolatey
    - Windows
dependencies: []
