# roles/helm/meta/main.yml
---
galaxy_info:
  role_name: helm
  author: A&ECoding
  description: Install Helm package manager for Kubernetes
  company: A&ECoding
  
  license: MIT
  
  min_ansible_version: "2.9"
  
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  
  galaxy_tags:
    - helm
    - kubernetes
    - k8s
    - package-manager
    - deployment
    - devops
    - container
    - orchestration

dependencies: []